<div id="sequra_splitpayments_teaser"></div>
<script type="text/x-magento-init">
    {
        "#sequra_splitpayments_teaser": {
            "Sequra_Core/js/widget-js": {
                "max_amount": "<?php echo (int)$block->getMaxOrderTotal();?>",
                "css_price_selector": "<?php echo addslashes($block->getData('price_sel')?:"");?>",
                "css_dest_selector": "<?php echo addslashes($block->getData('dest_sel')?:'#sequra_splitpayments_teaser');?>",
                "theme": "<?php echo addslashes($block->getData('theme')?:"");?>",
                "product": "<?php echo addslashes($block->getProduct());?>",
                "sequra_configuration":{
                    "merchant": "<?php echo $block->getMerchantRef(); ?>",
                    "assetKey": "<?php echo $block->getAssetsKey(); ?>",
                    "products": ["i1","pp3","pp5","pp6","pp9","sp1"],
                    "scriptUri": "<?php echo $block->getScriptUri(); ?>",
                    "decimalSeparator": "<?php echo $block->getDecimalSeparator(); ?>",
                    "thousandSeparator": "<?php echo $block->getThousandsSeparator(); ?>",
                    "locale": "<?php echo $block->getLocale(); ?>"
                }
            }
        }
    }
</script>
